backend:
  name: github
  repo: Das-Zelt/das-zelt.github.io
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Programm"
    label_singular: "Programmpunkt"
    name: "programm"
    folder: "src/programm"
    create: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Start", name: "start", widget: "datetime" }
      - { label: "Ende", name: "end", widget: "datetime" }
      - { label: "Beschreibung", name: "body", widget: "markdown" }
  - label: "Neuigkeiten"
    label_singular: "Neuigkeit"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
      - widget: select
        label: "Tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Einstellungen"
    label_singular: "Einstellung"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Beschriftung, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
